//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid Task_ID { get; set; }
        public System.Guid Parent_ID { get; set; }
        public string Task1 { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public int Priority { get; set; }
    
        public virtual ParentTask ParentTask { get; set; }
    }
}
